name: build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name for push
        run: echo "normalized_branch_name=$(stripped=${GITHUB_REF##*/} && echo ${stripped/\//-})" >> $GITHUB_ENV
        if: github.event_name == 'push'
      - name: Extract branch name for pull request
        run: echo "normalized_branch_name=$(stripped=${PR_REF#refs/heads/} && echo ${stripped/\//-})" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
        env:
          PR_REF: ${{ github.event.pull_request.head.ref }}
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
      - name: Push SHA to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ env.normalized_branch_name }}
            ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ github.sha }}
