name: build
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        run: echo "normalized_branch_name=$(stripped=${GITHUB_REF#refs/heads/} && echo ${stripped/\//-})" >> $GITHUB_ENV
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up the Python environment
        uses: actions/setup-python@v2
      - name: Lints the codebase
        uses: pre-commit/action@v2.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
      - name: Push SHA to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:latest
            ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ env.normalized_branch_name }}
            ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ github.sha }}
